imu_params:
  orientation_threshold:
    "x_threshold": 0.009
    "y_threshold": 0.004
    "z_threshold": 0.001
    "w_threshold": 1.001
  angular_velocity_threshold:
    "x_threshold": 0.0
    "y_threshold": 0.0
    "z_threshold": 0.0
  linear_acceleration_threshold:
    "x_threshold": 0.0
    "y_threshold": 0.0
    "z_threshold": 0.0

